### ISSUE TITLE
Load Gen fails sending data to https address - insecure platform warning

### ISSUE THREAD

**Issue by seethedata** [ktelep/tilt#16]
When running the load gen script after the recent SSL changes with the core TiLT application, the load gen script throws the following error:

https://tilt.cfapps.io/send
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not ava
ilable. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a n
ewer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatfor
mwarning.
  InsecurePlatformWarning

**Comment by ktelep** [comment]
Your platform is insecure, I suggest updating to Python 2.7.12 at least.
